const options = [
  { value: "Apple", label: "Apple" },
  { value: "Banana", label: "Banana" },
  { value: "Orange", label: "Orange" },
  { value: "Mango", label: "Mango" },
  { value: "Pear", label: "Pear" },
  { value: "Pineapple", label: "Pineapple" },
  { value: "Strawberry", label: "Strawberry" },
  { value: "Watermelon", label: "Watermelon" },
  { value: "Grape", label: "Grape" },
  { value: "Cherry", label: "Cherry" },
  { value: "Lemon", label: "Lemon" },
  { value: "Peach", label: "Peach" },
  { value: "Raspberry", label: "Raspberry" },
  { value: "Blueberry", label: "Blueberry" },
  { value: "Blackberry", label: "Blackberry" },
  { value: "Kiwi", label: "Kiwi" },
  { value: "Papaya", label: "Papaya" },
  { value: "Pomegranate", label: "Pomegranate" },
  { value: "Coconut", label: "Coconut" },
  { value: "Avocado", label: "Avocado" },
  { value: "Cranberry", label: "Cranberry" },
  { value: "Apricot", label: "Apricot" },
  { value: "Mandarin", label: "Mandarin" },
  { value: "Tangerine", label: "Tangerine" },
  { value: "Cantaloupe", label: "Cantaloupe" },
  { value: "Honeydew", label: "Honeydew" },
  { value: "Guava", label: "Guava" },
  { value: "Fig", label: "Fig" },
  { value: "Jackfruit", label: "Jackfruit" },
  { value: "Lychee", label: "Lychee" },
  { value: "Mango", label: "Mango" },
  { value: "Melon", label: "Melon" },
  { value: "Nectarine", label: "Nectarine" },
  { value: "Plum", label: "Plum" },
  { value: "Pomegranate", label: "Pomegranate" },
  { value: "Rambutan", label: "Rambutan" },
  { value: "Starfruit", label: "Starfruit" },
  { value: "Tomato", label: "Tomato" },
  { value: "Tamarind", label: "Tamarind" },
  { value: "Ugli Fruit", label: "Ugli Fruit" },
  { value: "Yuzu", label: "Yuzu" },
  { value: "Zucchini", label: "Zucchini" },
];

export default options;
